Refactor structure
Mentor-Whirlpool/mentor_whirlpool pull request #82
Opened 2022-08-17 12:11 UTC by A-Lazar-A

Рефактор тестовый, без удаления старых фалов но с заменой всех импортов на новые

2022-08-17 16:43 UTC, zinstack625 requested changes
Так сделать везде стоит
Причина:
1. Лишний шаг при поиска источника импорта. По виду импорта должно быть сразу понятно откуда он происходит по возможности
2. Явная предрасположенность к циклическим импортам

Ну и удалить старые файлы всё-таки стоит

2022-08-17 16:43 UTC, zinstack625 commented on mentor_whirlpool/admin_handle/edit_subject.py
> +from __init__ import types, Database, bot, logging, gather, AdminStates
Если такой ужас получается при импорте в __init__ лучше импорт всего здесь, даже если это добавит 5-6 строк

2022-08-17 19:35 UTC, A-Lazar-A commented
Исправил 
@zinstack625

2022-08-18 11:09 UTC, zinstack625 requested changes

2022-08-18 12:16 UTC, A-Lazar-A commented
check
@zinstack625

2022-08-18 21:41 UTC, zinstack625 approved these changes

2022-08-18 21:52 UTC, merged